"""
agents/reflection_agent.py — Reflection Agent (Mandatory Guardrail).

Audits output plans generated by PlannerAgent:
  - Validates daily time budget limits (prevents >14h / day impossible schedules).
  - Detects task packing overload risks.
  - Ensures prerequisite order compliance.
  - Can issue replan_required = True signals to trigger Orchestrator replanning.
"""

from __future__ import annotations

import logging
from typing import Optional

from app.agents.models import StructuredPlanModel, ReflectionValidationResult

logger = logging.getLogger(__name__)

# Daily maximum human study capacity in minutes (12 hours = 720 minutes)
MAX_DAILY_STUDY_MINUTES = 720


def review_plan(
    plan: StructuredPlanModel,
    max_budget_minutes: int = 480,
) -> ReflectionValidationResult:
    """
    Audits a StructuredPlanModel for feasibility, overload risks, and consistency.
    """
    warnings: list[str] = []
    recommendations: list[str] = []
    overload_risk = False
    replan_required = False

    total_minutes = sum(item.recommended_minutes for item in plan.items)

    if total_minutes > MAX_DAILY_STUDY_MINUTES:
        overload_risk = True
        replan_required = True
        warnings.append(f"Excessive daily workload requested ({total_minutes} mins exceeds 12-hour human ceiling).")
        recommendations.append("Cap study budget to maximum 6-8 hours and spread remaining tasks over future days.")

    if len(plan.items) > 10:
        overload_risk = True
        warnings.append("High context switching risk (more than 10 distinct task sessions in one day).")
        recommendations.append("Consolidate session allocations into 3-5 focus blocks for better retention.")

    if not plan.items:
        warnings.append("Plan contains zero scheduled items.")

    confidence = 0.95 if not warnings else (0.70 if replan_required else 0.85)

    result = ReflectionValidationResult(
        is_valid=not replan_required,
        replan_required=replan_required,
        overload_risk=overload_risk,
        confidence_score=confidence,
        warnings=warnings,
        recommendations=recommendations,
    )

    logger.info("ReflectionAgent: Validated plan valid=%s replan_required=%s", result.is_valid, result.replan_required)
    return result
