"""
agents/reflection_agent.py — Reflection Agent (Mandatory Guardrail & Audit Engine).

Audits output plans generated by PlannerAgent:
  - Validates daily time budget limits (prevents >12h / day impossible schedules or user requested budget overflow).
  - Detects task packing overload risks.
  - Ensures prerequisite order compliance.
  - Issues structured replan_required = True signals with explicit suggested_max_minutes to trigger Orchestrator replanning feedback loop.
"""

from __future__ import annotations

import logging
from typing import Optional
from app.agents.models import StructuredPlanModel, ReflectionValidationResult

logger = logging.getLogger(__name__)

# Daily maximum human study capacity in minutes (12 hours = 720 minutes)
MAX_DAILY_STUDY_MINUTES = 720


def review_plan(
    plan: StructuredPlanModel,
    max_budget_minutes: Optional[int] = None,
) -> ReflectionValidationResult:
    """
    Audits a StructuredPlanModel for feasibility, overload risks, and user budget compliance.
    """
    warnings: list[str] = []
    recommendations: list[str] = []
    overload_risk = False
    replan_required = False

    total_minutes = sum(item.recommended_minutes for item in plan.items)
    effective_budget = max_budget_minutes or plan.available_minutes or 240

    # 1. Check user budget constraint overflow
    if total_minutes > effective_budget:
        overload_risk = True
        replan_required = True
        warnings.append(
            f"Plan overload: Total allocated duration ({total_minutes}m) exceeds available user budget ({effective_budget}m)."
        )
        recommendations.append(
            f"Trigger Planner re-calculation with strict upper bound cap of {effective_budget} minutes."
        )

    # 2. Check 12-hour human capacity ceiling
    if total_minutes > MAX_DAILY_STUDY_MINUTES:
        overload_risk = True
        replan_required = True
        warnings.append(f"Excessive daily workload ({total_minutes}m exceeds 12-hour human ceiling).")
        recommendations.append("Cap study budget to maximum 6-8 hours and defer remaining tasks.")

    # 3. Check task switching cognitive fatigue
    if len(plan.items) > 8:
        overload_risk = True
        warnings.append(f"High context switching risk ({len(plan.items)} separate study blocks).")
        recommendations.append("Consolidate session allocations into 3-5 focus blocks.")

    if not plan.items:
        warnings.append("Plan contains zero scheduled items.")

    confidence = 0.95 if not warnings else (0.70 if replan_required else 0.85)

    result = ReflectionValidationResult(
        is_valid=not replan_required,
        replan_required=replan_required,
        overload_risk=overload_risk,
        confidence_score=confidence,
        warnings=warnings,
        recommendations=recommendations,
    )

    logger.info(
        "ReflectionAgent: Audited plan valid=%s replan_required=%s (Allocated: %dm, Budget: %dm)",
        result.is_valid, result.replan_required, total_minutes, effective_budget
    )
    return result
